version: "3.8"

services:
  strapi:
    image: node:20
    container_name: smartopea-strapi
    working_dir: /srv/app
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run develop"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: smartopea-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartopea
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: